AsishRaju/450-DSA

package-lock.json, package.json, src/App.js
There was a mismatch of the Backtracking topic with a stack topic. When you open the backtracking topic route you will see questions related to stacks. It was due to the wrong position index in the Route component.
Hope this pull request solves the problem.
=> Fixed the route mismatch of Backtracking and stack topic.

package-lock.json, package.json, src/components/Topic/Topic.css, src/components/Topic/Topic.js
Logic for the notifications contained in a `displayToast` function in `Topic.js`. Added an extra CSS sheet for notification styling named `Topic.css` although not sure where you'd want these styles ideally!
The `ToastContainer` component can go anywhere in the tree but decided to keep it in `Topic.js` for the time being since that's where it's being used at the moment. Hope this is more or less what you were looking for :)
=> Add select/unselect notifications

src/450DSAFinal.js
Fixed typo on 23 and 24
- Changed question link on 24 because GFG practice link is restricted for this question
=> Fixed typo and link for array question 23/24

README.md, package-lock.json, package.json
I've added the correct commands required to start the server from the location as the server starts inside the src folder and not the base folder
=> Fixed the cloning and run server operations

src/450DSAFinal.js
The Question in the practice.geeksforgeeks.org is different from the question title.
=> Question URL correction

src/450DSAFinal.js
Removed the 3 stack and queue questions in Backtracking topic.
=> fix: removed stack questions in backtracking topic

src/components/TopicCard/TopicCard.js
added a progress bar to show progress for complete 450 questions , the progress bar is fluid and no issues with responsiveness.
adding some screenshots of the enhancement.
Also if the user has not started with any questions then the progress bar won't be displayed.
=> added total ques progress bar

src/450DSAFinal.js, src/components/Topic/Topic.css, src/components/Topic/Topic.js, src/services/dbServices.js
Added notes section for each question to take quick notes up to 50 words , made it responsive for mobile view too.
The notes is getting stored in the local db itself .
Mobile view 
in mobile view the notes can be viewed in the popup itself by clicking the  add note button
=> added notes section

src/450DSAFinal.js
Updated the link to the problem on leetcode
=> Updated question Link

src/450DSAFinal.js
The link to the hackerrank problem Bishu and Soldiers were not working. So it has been updated to the correct link.
=> Added the correct link for the problem no. 18 of Searching and Sorting

src/450DSAFinal.js, src/services/dbServices.js
async function added for updation of data
=> fix to lenght of notes not defined

src/450DSAFinal.js, src/services/dbServices.js
=> Revert "Update dbServices.js"

src/450DSAFinal.js, src/services/dbServices.js
=> Revert "fix to lenght of notes not defined"

src/450DSAFinal.js, src/components/Topic/Topic.js
=> fixed notes deleted on save

src/components/Topic/Topic.js
issue #76 solved now the text area max length is 432 which is equal to the size of the space available in notes making section.
=> increased text area maxlength to size of the space in notes making section.  Issue #76

450DSA.json, src/450DSAFinal.js
Two Issues that I have tried to resolve
1. Word spacing in question-32 of string section
**Earlier**: Write a program tofind the smallest window that contains all characters of string itself.
**Now**: Write a program to **find** the smallest window that contains all characters of string itself.
2. Water Jug Problem in Graph Section is repeating twice so I have just deleted the redundant code. (Note: earlier someone has worked on this issue but those changes were not reflecting, so I though why not make another PR).
=> word spacing in ques-32 of string and water jug twice issue resolved

src/components/Topic/Topic.css, src/components/Topic/Topic.js
Issue #30 
Added **Pick a Random Question button** which will pick any random question from a particular category.
=> Added random button feature

src/components/Topic/Topic.js
Rendering SearchBar as a function rather than a component fixes the issue "Questions get disappeared #50"
=> Updated topic js to render SearchBar as a function

src/components/Topic/Topic.css, src/components/Topic/Topic.js
The button named "Pick Random" in the Topics Component was styled using React-Bootstrap which assigned the z-index of the button to be 2,so when we opened the notes Modal it still appears on the top of the notes division, which shouldn't be the case!
I have added class named "pick-named-btn"  and targeted it using the external style sheet and updated the z-index of the whole button to 0 and to override the z-index added by React-Bootstrap , I have added an "Important" at the end.
All the other changes that you will see was because i have "Prettier" installed and it made the code more pretty without writing any extra code, but it is included in changes because it removed some of the white spaces and added where needed.
=> Pick Random Button z-index Updated Fixes #98

src/components/Topic/Topic.js
The "Pick Random" button attribute "href" was not a state variable and because of that it keep suggesting the same question unless re render is triggered and there was no such functionality for re rendering the component on clicking the button.
In this PR i have created a separate component for the "Pick Random" button and created a state variable for the "href" attribute and created an onClick functionality which changes the value of that state variable on clicking the button and since the state is changed the re render is triggered and fixes #100 .
=> Fixed the functionality of the pick random button

src/450DSAFinal.js
- Updated gold mine problem link as previous its taking to the artcile page instead of the practice page
=> Update a problem Link

src/App.css, src/components/About/About.js, src/components/Footer/Footer.js, src/components/Topic/Topic.css, src/components/Topic/Topic.js, src/components/TopicCard/TopicCard.js, src/components/TopicCard/topicCard.css
There should be a feature that when you are inside a particular topic you can see how many questions are done.
I Have added a paragraph in the right of the "Pick Random" button which shows how many questions are done and also shows the total no of questions which fixes #97 .
Prettier Has re arranged some lines of codes which changing the content ,it just added some white spaces so that is the reason why you will see some code which seems to be changed but when you look at the changed code its actually the same !!
=> New feature No of Completed Questions In The Topics Section

src/450DSAFinal.js
Minimum size subarray problem is no more available on GFG. Hence, updated the Leetcode link for the same.
@AsishRaju have a look
=> Updated a problem in array

450DSA.json
there was only code url given , i have added one more qoestion for the practice
=> updated 0th question in graph section

src/450DSAFinal.js
Hi!
There is no practice.geeksforgeeks.org link for the Problem 35 in Arrays. I found a Leetcode Questions for the similar question and replaced it. Do take a look!
=> Replaced the link of Q35 in Arrays with Leetcode

src/450DSAFinal.js
Findthe inversion count---> Find the inversion count
=> Fixed Typo

src/450DSAFinal.js
Hi! 
I've updated the practice links for the following questions. These questions had a Geeks for Geeks article initially. After merging, they'll have online IDE links to those questions.
=> Updated Links of Questions with GfG Practice and LeetCode alternatives

450DSA.json, src/450DSAFinal.js
Topic:-Greedy
problem:- activity-selection
https://practice.geeksforgeeks.org/problems/activity-selection-1587115620/1/
update link,
after clicking  on` activity-selection problem` it's show `N meetings in one room  problem` , you can update link of` activity-selection` and also add `N meetings in one room` problem
=> activity-selection link update

src/450DSAFinal.js
Regarding issue no #146 
Please review it
=> Links update

450DSA.json
replaces geeksforgeeks article link with practice link for Construct Binary Tree from String with bracket representation in binary tree topic
=> replaces geeksforgeeks article link with practice link

450DSA.json
=> Update link of problem

450DSA.json
=> Update with new url

450DSA.json
Problem: Convert a Sentence into its equivalent mobile numeric keypad sequence.
=> Update Url with new working url

450DSA.json
Searching in an array where adjacent differ by
=> Update problem link :
